name: build

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          source-url: "https://github.com/DeterminateSystems/nix-installer/releases/download/v3.0.0/nix-installer-x86_64-linux"
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Unit tests
        run: nix develop --command dotnet test
